CREATE TABLE PRODUCTO (
    IDPRODUCTO INT NOT NULL,
    IDGRUPO INT NOT NULL,
    MARCA VARCHAR(25),
    CLAVE_EXTERNA VARCHAR(25),
    UBICACION VARCHAR(25),
    PRECIO INT,
    EXISTENCIAS INT,
    IDESTANDAR INT NOT NULL,
    PRIMARY KEY (IDPRODUCTO)
);


CREATE TABLE PROD_VENDIDO (
    IDFACTURA INT NOT NULL,
    IDPRODUCTO INT NOT NULL,
    PRECIO INT,
    CANTIDAD INT,
    PRIMARY KEY (IDFACTURA, IDPRODUCTO)
);


CREATE TABLE FACTURA (
    IDFACTURA INT NOT NULL,
    IDFOLIO VARCHAR(25),
    IDFECHA DATE,
    IVA INT,
    IMPORTE INT,
    TIPO_FACTURA VARCHAR(25),
    SALDO INT,
    IDCLIENTE INT NOT NULL,
    IDPAGO INT,
    PRIMARY KEY (IDFACTURA)
);


CREATE TABLE CLIENTE(
    IDCLIENTE INT NOT NULL,
    RFC VARCHAR(25),
    NOMBRE VARCHAR(25),
    CALLE VARCHAR(25),
    NUMERO VARCHAR(25),
    COLONIA VARCHAR(25),
    CP VARCHAR(25),
    MUNICIPIO VARCHAR(25),
    LADA1 VARCHAR(25),
    TELEFONO1 VARCHAR(25),
    LADA2 VARCHAR(25),
    TELEFONO2 VARCHAR(25),
    SALDO INT,
    PRIMARY KEY (IDCLIENTE)
);


CREATE TABLE PROD_PEDIDO (
    IDPRODUCTO INT NOT NULL,
    IDPEDIDO INT NOT NULL,
    COSTO DECIMAL(15, 2),
    CANTIDAD INT,
    PRIMARY KEY (IDPRODUCTO, IDPEDIDO)
);


CREATE TABLE PEDIDO (
    IDPEDIDO INT NOT NULL,
    FECHA_PEDIDO DATE,
    IMPORTE INT,
    FECHA_RECIBIDO DATE,
    IVA INT,
    IDPROVEEDOR INT NOT NULL,
    PRIMARY KEY (IDPEDIDO)
);


CREATE TABLE PROVEEDOR (
    IDPROVEEDOR INT NOT NULL,
    RFC VARCHAR(25),
    NOMBRE VARCHAR(25),
    CALLE VARCHAR(25),
    NUMERO VARCHAR(25),
    COLONIA VARCHAR(25),
    REFERENCIAS VARCHAR(25),
    CP VARCHAR(25),
    MUNICIPIO VARCHAR(25),
    LADA VARCHAR(25),
    TELEFONO VARCHAR(25),
    PRIMARY KEY (IDPROVEEDOR)
);


CREATE TABLE CONTACTO_PROVEEDOR (
    IDPROVEEDOR INT NOT NULL,
    IDCONTACTO INT NOT NULL,
    NOMBRE VARCHAR(25),
    APPATERNO VARCHAR(25),
    APMATERNO VARCHAR(25),
    CARGO VARCHAR(25),
    EXTENSION VARCHAR(25),
    LADA2 VARCHAR(25),
    TELEFONO2 VARCHAR(25),
    PRIMARY KEY (IDPROVEEDOR, IDCONTACTO)
);


CREATE TABLE PROD_SURTIDO(
    IDPRODUCTO INT NOT NULL,
    IDPROVEEDOR INT NOT NULL,
    PRIMARY KEY (IDPRODUCTO, IDPROVEEDOR)
);


CREATE TABLE ESTANDAR(
    IDESTANDAR INT NOT NULL,
    NOMBRE VARCHAR(25),
    PRIMARY KEY (IDESTANDAR)
);


CREATE TABLE AUTO_ESTANDAR(
    IDAUTOMOVIL INT NOT NULL,
    IDESTANDAR INT NOT NULL,
    PRIMARY KEY (IDAUTOMOVIL, IDESTANDAR)
);


CREATE TABLE AUTOMOVIL (
    IDAUTOMOVIL INT NOT NULL,
    IDMODELO INT NOT NULL,
    ANIO INT,
    MOTOR VARCHAR(25),
    PRIMARY KEY (IDAUTOMOVIL)
);


CREATE TABLE MODELO (
    IDMODELO INT NOT NULL,
    NOMBRE VARCHAR(25),
    FABRICANTE INT,
    PRIMARY KEY (IDMODELO)
);


CREATE TABLE GRUPO (
    IDGRUPO INT NOT NULL,
    NOMBRE VARCHAR(25),
    LINEA VARCHAR(25),
    UNIDAD VARCHAR(25),
    PRIMARY KEY (IDGRUPO)
);


--Enunciado SQL para relacion foranea
ALTER TABLE
    PROD_VENDIDO
ADD
    CONSTRAINT PROD_VENDIDO_FK FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO (IDPRODUCTO);


ALTER TABLE
    PROD_VENDIDO
ADD
    CONSTRAINT FACTURA_FK FOREIGN KEY (IDFACTURA) REFERENCES FACTURA (IDFACTURA);


ALTER TABLE
    FACTURA
ADD
    CONSTRAINT CLIETE_FK FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE);


ALTER TABLE
    PROD_PEDIDO
ADD
    CONSTRAINT PROD_PEDIDO_FK1 FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO (IDPRODUCTO);


ALTER TABLE
    PROD_PEDIDO
ADD
    CONSTRAINT PEDIDO_FK FOREIGN KEY (IDPEDIDO) REFERENCES PEDIDO (IDPEDIDO);


ALTER TABLE
    PEDIDO
ADD
    CONSTRAINT PROVEEDOR_FK FOREIGN KEY (IDPROVEEDOR) REFERENCES PROVEEDOR (IDPROVEEDOR);


ALTER TABLE
    PROD_SURTIDO
ADD
    CONSTRAINT PROD_SURTIDO_FK1 FOREIGN KEY (IDPROVEEDOR) REFERENCES PROVEEDOR (IDPROVEEDOR);


ALTER TABLE
    PROD_SURTIDO
ADD
    CONSTRAINT PROD_SURTIDO_FK2 FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO (IDPRODUCTO);


ALTER TABLE
    CONTACTO_PROVEEDOR
ADD
    CONSTRAINT CONTACTO_PROVEEDOR_FK FOREIGN KEY (IDPROVEEDOR) REFERENCES PROVEEDOR (IDPROVEEDOR);


ALTER TABLE
    PRODUCTO
ADD
    CONSTRAINT ESTANDAR_FK FOREIGN KEY (IDESTANDAR) REFERENCES ESTANDAR (IDESTANDAR);


ALTER TABLE
    AUTO_ESTANDAR
ADD
    CONSTRAINT AUTO_ESTANDAR_FK1 FOREIGN KEY (IDESTANDAR) REFERENCES ESTANDAR (IDESTANDAR);


ALTER TABLE
    AUTO_ESTANDAR
ADD
    CONSTRAINT AUTOMOVIL_FK2 FOREIGN KEY (IDAUTOMOVIL) REFERENCES AUTOMOVIL (IDAUTOMOVIL);


ALTER TABLE
    AUTOMOVIL
ADD
    CONSTRAINT MODELEO_FK FOREIGN KEY (IDMODELO) REFERENCES MODELO (IDMODELO);


ALTER TABLE
    PRODUCTO
ADD
    CONSTRAINT GRUPO_FK FOREIGN KEY (IDGRUPO) REFERENCES GRUPO (IDGRUPO);